apiVersion: apps/v1
kind: Deployment
metadata: 
  name: conversao-temperatura
  labels:
    app: conversao
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: conversao-api
          image: ruffab/conversao-temperatura:v1
          ports: 
            - containerPort: 8080